### ISSUE TITLE
transform example does not work

### ISSUE THREAD

**Issue by sparkofreason** [halgari/odin#10]
The `transform` example in README throws an error. First problem seems to be that it was not passed `data`. But even after adding that I get this exception:

java.lang.ClassCastException: com.tbaldridge.odin.unification.LVar cannot be cast to java.lang.Number
	at clojure.lang.Numbers.equiv(Numbers.java:208)
	at com.tbaldridge.odin$update.invokeStatic(odin.clj:120)
	at com.tbaldridge.odin$update.invoke(odin.clj:118)

**Comment by sparkofreason** [comment]
Do you mean to use `==` in the 1-arity version of `com.tbaldridge.odin/update`? Changing to `=` does fix this particular issue, though don't know if that breaks something else.
